---
- name: Install additional software
  ansible.builtin.apt:
    name:
      - gdisk
      - libnfs-utils
      - rsync
      - tar
      - tuned
      - tcpdump
      - vim
      - tmux
      - sudo
    state: present

- name: Find persistent-net.rules
  ansible.builtin.find:
    paths: /etc/udev/rules.d
    patterns: 70*
  register: net_rules

- name: Delete persistent-net.rules
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: absent
  with_items: "{{ net_rules.files }}"

- name: Configure /etc/vim/vimrc
  ansible.builtin.copy:
    src: vimrc
    dest: /etc/vim/vimrc
    owner: root
    group: root
    mode: 0644

- name: Configure /etc/ssh/sshd_config
  ansible.builtin.copy:
    src: sshd_config
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: 0644

- name: Configure /etc/network/interfaces
  ansible.builtin.copy:
    src: interfaces
    dest: /etc/network/interfaces
    owner: root
    group: root
    mode: 0644

- name: Configure /etc/default/grub
  ansible.builtin.copy:
    src: grub
    dest: /etc/default/grub
    owner: root
    group: root
    mode: 0644

- name: Update /boot/grub/grub.cfg
  ansible.builtin.shell: grub-mkconfig -o /boot/grub/grub.cfg

- name: Enable serial console
  ansible.builtin.systemd_service:
    name: serial-getty@ttyS0
    state: started
    enabled: true

- name: Disable consistent network device naming
  ansible.builtin.file:
    src: /dev/null
    dest: /etc/udev/rules.d/80-net-name-slot.rules
    owner: root
    group: root
    state: link

- name: Disable virtual terminals allocation by logind
  ansible.builtin.replace:
    path: "/etc/systemd/logind.conf"
    regexp: '^#?NAutoVTs=\d+'
    replace: "NAutoVTs=0"

- name: Change file ownership, group and permissions /etc/sudoers
  ansible.builtin.file:
    path: /etc/sudoers
    owner: root
    group: root
    mode: 0644

- name: Add debian user to /etc/sudoers
  ansible.builtin.lineinfile:
    path: /etc/sudoers
    line: "debian\tALL=(ALL)\tNOPASSWD: ALL"
    state: present

- name: Change file ownership, group and permissions /etc/sudoers
  ansible.builtin.file:
    path: /etc/sudoers
    owner: root
    group: root
    mode: 0440

- name: Disable root login
  ansible.builtin.user:
    name: root
    password: "!!"