---


- name: Install additional software
  apt:
    name:
      - cockpit-system
      - cockpit-ws
      - gdisk
      - libnfs-utils
      - rsync
      - tar
      - tuned
      - tcpdump
      - vim
      - tmux
      - sudo
    state: present

- name: Find persistent-net.rules
  find:
    paths: /etc/udev/rules.d
    patterns: 70*
  register: net_rules

- name: Delete persistent-net.rules
  file:
    path: "{{ item.path }}"
    state: absent
  with_items: "{{ net_rules.files }}"

- name: Configure /etc/vim/vimrc
  copy:
    src: vimrc
    dest: /etc/vim/vimrc
    owner: root
    group: root
    mode: 0644

- name: Configure /etc/network/interfaces
  copy:
    src: interfaces
    dest: /etc/network/interfaces
    owner: root
    group: root
    mode: 0644


- name: Configure /etc/default/grub
  copy:
    src: grub
    dest: /etc/default/grub
    owner: root
    group: root
    mode: 0644

- name: Update /boot/grub/grub.cfg
  shell: grub-mkconfig -o /boot/grub/grub.cfg

- name: Disable consistent network device naming
  file:
    src: /dev/null
    dest: /etc/udev/rules.d/80-net-name-slot.rules
    owner: root
    group: root
    state: link

- name: Disable virtual terminals allocation by logind
  replace:
    path: '/etc/systemd/logind.conf'
    regexp: '^#?NAutoVTs=\d+'
    replace: 'NAutoVTs=0'

- name: Change file ownership, group and permissions /etc/sudoers
  file:
    path: /etc/sudoers
    owner: root
    group: root
    mode: 0644

- name: Add debian user to /etc/sudoers
  lineinfile:
    path: /etc/sudoers
    line: "debian\tALL=(ALL)\tNOPASSWD: ALL"
    state: present

- name: Change file ownership, group and permissions /etc/sudoers
  file:
    path: /etc/sudoers
    owner: root
    group: root
    mode: 0440

- name: Disable root login
  user:
    name: root
    password: '!!'