# An Ansible playbook that configures a Generic Cloud (OpenStack) image
---
- name: Debian Generic Cloud by ojpojao - iON Telecom
  hosts: default
  become: yes
  become_method: su
  roles:
    - gencloud_guest
    - cleanup_vm